[project]
name = "ezlang"
version = "0.1.0"
description = "EzLang 编程语言工具链"
main = "examples/types.ez"
public = true
registry = "dist/registry"
optimize = 2

[log]
compile_min_level = 2

[workspace]
members = ["packages/*"]

[[output]]
arch = "x86_64"
os = "linux"
dir = "dist/linux-x86_64"

[[output]]
arch = "aarch64"
os = "macos"
dir = "dist/macos-aarch64"

[[output]]
arch = "x86_64"
os = "macos"
dir = "dist/macos-x86_64"

[[output]]
arch = "wasm32"
os = "emcc"
dir = "dist/emcc-wasm32"

[deps]
std = "./packages/std"
ez-web-ui = "./packages/ez-web-ui"
ez-android-ui = "./packages/ez-android-ui"
ez-ios-ui = "./packages/ez-ios-ui"
